// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(MyApplicationDbContext))]
    [Migration("20221006224434_Creation_Tables")]
    partial class Creation_Tables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domaine.MyEntities.Numero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Valeur")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Valeur")
                        .IsUnique();

                    b.ToTable("Numeros");
                });

            modelBuilder.Entity("Domaine.MyEntities.TirageLoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("TiragesLoto");
                });

            modelBuilder.Entity("NumeroTirageLoto", b =>
                {
                    b.Property<int>("NumerosId")
                        .HasColumnType("int");

                    b.Property<int>("TiragesId")
                        .HasColumnType("int");

                    b.HasKey("NumerosId", "TiragesId");

                    b.HasIndex("TiragesId");

                    b.ToTable("NumeroTirageLoto");
                });

            modelBuilder.Entity("NumeroTirageLoto", b =>
                {
                    b.HasOne("Domaine.MyEntities.Numero", null)
                        .WithMany()
                        .HasForeignKey("NumerosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domaine.MyEntities.TirageLoto", null)
                        .WithMany()
                        .HasForeignKey("TiragesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
